version: '3.8'

services:
  db:
    image: postgres:15
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: career_compass
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/career_compass?schema=public
      NODE_ENV: development
    ports:
      - "3001:3001"
    command: |
      sh -c "
        npx prisma migrate deploy &&
        node dist/main.js
      "

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  db_data:
